Meltsova_V_ 214Б
SkiStalker/FundAlg3Sem pull request #12
Opened 2024-10-23 09:43 UTC by Nichichik

Added 3, 4, 7, 8 tasks from 2 laboratory work

2024-10-30 13:28 UTC, SkiStalker requested changes

2024-10-30 13:28 UTC, SkiStalker commented on lb2/task7/lb2task7.c
> +        if (func(c) == 0.0) {
Тут должно быть сравнение по эпсилон
```suggestion
        if (fabs(func(c)) < epsilon>) {
```

2024-10-30 13:28 UTC, SkiStalker commented on lb2/task7/lb2task7.c
> +    while ((b - a) / 2 > epsilon) {
Зачем здесь делить длину отрезка пополам, в определении дихотомии этого правила нет
```suggestion
    while ((b - a) > epsilon) {
```

2024-10-30 13:28 UTC, SkiStalker commented on lb2/task7/lb2task7.c
> +double func3(double x) {
Где то эти функции я уже видел

2024-10-30 13:28 UTC, SkiStalker commented on lb3/task2/lb3task2.c
> +} Vector;
В Си обычно структуры не называют с большой буквы

```suggestion
} vector_t;
```

2024-10-30 13:28 UTC, SkiStalker commented on lb3/task3/lb3task3.c
> +}Employee;
Тот же косяк
```suggestion
} employee_t;
```

2024-10-30 13:28 UTC, SkiStalker commented on lb3/task3/lb3task3.c
> +ErrorCode pars_arg(int argc, char* argv[], char** input_file, char** output_file, char* sort_flag) {
Почему не parse_args
```suggestion
ErrorCode parse_args(int argc, char* argv[], char** input_file, char** output_file, char* sort_flag) {
```

2024-10-30 13:28 UTC, SkiStalker commented on lb3/task3/lb3task3.c
> +    if (surnameComp != 0) return surnameComp;
Нужен перенос на новую строку

2024-10-30 13:28 UTC, SkiStalker commented on lb3/task3/Makefile
> +TEST_TEMPLATES_DIR=/mnt/c/Users/Вероника/Documents/GitHub/FundAlg3Sem/test_templates
Опять абсолютный путь(
```suggestion
TEST_TEMPLATES_DIR=../../test_templates
```

2024-10-30 13:28 UTC, SkiStalker requested changes
2 лабу всю принял в 3 лабе 1 и 2 задание в 3 все ок (я бы даже сказал слишком ок, код мне понравился) но надо поправить Makefile

2024-11-06 22:55 UTC, Nichichik commented
add lb3:task 4, 8, 10

2024-11-08 12:29 UTC, SkiStalker commented
Лабы 4, 8 и 10 из 3 лабы зачтены

2024-11-08 12:29 UTC, closed without merging